Traceback (most recent call last):
  File "/data/data/com.termux/files/home/GrowthMasterVIP/GrowthMasterVip/control_vip.py", line 78, in <module>
    bot.send_message(TOKEN.split(":")[0], "âœ… Bot GrowthMaster VIP iniciado correctamente.")
  File "/data/data/com.termux/files/usr/lib/python3.12/site-packages/telebot/__init__.py", line 1800, in send_message
    apihelper.send_message(
  File "/data/data/com.termux/files/usr/lib/python3.12/site-packages/telebot/apihelper.py", line 275, in send_message
    return _make_request(token, method_url, params=payload, method='post')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.12/site-packages/telebot/apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.12/site-packages/telebot/apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 403. Description: Forbidden: bots can't send messages to bots
